language: python
python:
  - "3.5"

sudo: true

before_install:
  - wget -O - http://binaries.erlang-solutions.com/debian/erlang_solutions.asc | sudo apt-key add -
  - sudo add-apt-repository ppa:eugenesan/ppa -y
  - sudo apt-get update
  - sudo apt-get install erlang -y
  - sudo apt-get install php5 -y
  - sudo apt-get install golang -y
  - sudo apt-get install clojure -y
  - sudo apt-get install ghc -y
  - sudo apt-get install g++ gcc -y
  - sudo apt-get install lua5.2 -y
  - sudo apt-get install ruby-full -y
  - sudo apt-get install clisp -y
  - sudo pip install cython

install:
  - pip install -r requirements.txt

script: python stats.py --search python --build   
                        --search commonlisp  
                        --search ruby 
                        --search haskell
                        --search clojure
                        --search go
                        --search php 
                        --search python
                        --search elixir
                        --search lua
                        --search bash
  
  