version: "2"

services:
  runner:
    image: destructhub/project_euler
    command: elixir --no-halt stats.exs -s python
                                        -s commonlisp
                                        -s ruby
                                        -s haskell
                                        -s go
                                        -s php
                                        -s elixir
                                        -s lua
                                        -s c++
                                        -s bash
                                        -s clojure
                                        -s c
    volumes:
      - .:/code
